site_name: Complex Security
theme:
  name: material
  custom_dir: overrides
  favicon: images/favicon.png
  language: en
  icon:
    logo: fontawesome/brands/hackerrank
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - header.autohide
    - announce.dismiss
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest

  plugins:
    - typeset
    - search

  palette:
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true

copyright: Copyright &copy; 2024 Jonathan Pake
extra_css:
  - stylesheets/extra.css
extra:
  generator: false

nav:
  - Home: https://kenharris.io
  - Cheatsheets:
      - "Start Here":
          - "Start Here": cheatsheets.md
      - "Cheatsheets":
          - "Active Directory Pentesting Cheatsheet": cheatsheets/active-directory-pentesting-cheatsheet.md
          - "Bash Scripting": cheatsheets/bash-scripting.md
          - "Chrome URLs/Flags": cheatsheets/chrome-urls-flags.md
          - "Default Credentials": cheatsheets/default-credentials.md
          - "Exchange Versions": cheatsheets/exchange-versions.md
          - "Github Dorks": cheatsheets/github-dorks.md
          - "Google Dorks": cheatsheets/google-dorks.md
          - "Headers & Files": cheatsheets/headers-files.md
          - "List of TLDs": cheatsheets/list-of-tlds.md
          - "Miscellaneous": cheatsheets/miscellaneous.md
          - "Netmasks & Subnetting": cheatsheets/networking-subnetting.md
          - "PrivEsc Mindmap": cheatsheets/privesc-mindmap.md
          - "RegEx": cheatsheets/regex.md
          - "Windows Security Log References": cheatsheets/windows-security-log-references.md
          - "XSS": cheatsheets/xss.md
          - "XML External Entity Injection": cheatsheets/xml-xxe.md
  - CVEs:
      - "Start Here":
          - "Start Here": cves.md
      - "CVEs":
          - "CVE-2007-1036": cves/CVE-2007-1036.md
          - "CVE-2012-0002": cves/CVE-2012-0002.md
          - "CVE-2012-1675": cves/CVE-2012-1675.md
          - "CVE-2013-4786": cves/CVE-2013-4786.md
          - "CVE-2014-0224": cves/CVE-2014-0224.md
          - "CVE-2014-6321": cves/CVE-2014-6321.md
          - "CVE-2014-8272": cves/CVE-2014-8272.md
          - "CVE-2016-1287": cves/CVE-2016-1287.md
          - "CVE-2016-2107": cves/CVE-2016-2107.md
          - "CVE-2017-0143": cves/CVE-2017-0143.md
          - "CVE-2017-8917": cves/CVE-2017-8917.md
          - "CVE-2017-12542": cves/CVE-2017-12542.md
          - "CVE-2018-10993": cves/CVE-2018-10993.md
          - "CVE-2019-0686": cves/CVE-2019-0686.md
          - "CVE-2019-0708": cves/CVE-2019-0708.md
          - "CVE-2019-2725": cves/CVE-2019-2725.md
          - "CVE-2019-5392": cves/CVE-2019-5392.md
          - "CVE-2019-18935": cves/CVE-2019-18935.md
          - "CVE-2019-19781": cves/CVE-2019-19781.md
          - "CVE-2020-0609": cves/CVE-2020-0609.md
          - "CVE-2020-0796": cves/CVE-2020-0796.md
          - "CVE-2020-1350": cves/CVE-2020-1350.md
          - "CVE-2020-1472": cves/CVE-2020-1472.md
          - "CVE-2020-5902": cves/CVE-2020-5902.md
          - "CVE-2020-10487": cves/CVE-2020-10487.md
          - "CVE-2020-14882": cves/CVE-2020-14882.md
          - "CVE-2021-4034": cves/CVE-2021-4034.md
          - "CVE-2021-26855": cves/CVE-2021-26855.md
          - "CVE-2021-27850": cves/CVE-2021-27850.md
          - "CVE-2021-34473": cves/CVE-2021-34473.md
          - "CVE-2021-34527": cves/CVE-2021-34527.md
          - "CVE-2021-40449": cves/CVE-2021-40449.md
          - "CVE-2021-44228": cves/CVE-2021-44228.md
          - "CVE-2022-0847": cves/CVE-2022-0847.md
          - "CVE-2022-21882": cves/CVE-2022-21882.md
          - "CVE-2022-30190": cves/CVE-2022-30190.md
  - Commands:
      - "Start Here":
          - "Start Here": commands.md
      - "MacOS Commands":
          - "Caffeinate": macos/caffeinate.md
          - "Ditto": macos/ditto.md
          - "Firmwarepasswd": macos/firmwarepasswd.md
          - "ipconfig": macos/ipconfig.md
          - "networkquality": macos/networkquality.md
          - "powermetrics": macos/powermetrics.md
          - "scutil": macos/scutil.md
          - "security": macos/security.md
          - "sha2": macos/sha2.md
          - "softwareupdate": macos/softwareupdate.md
          - "spctl": macos/spctl.md
          - "system_profiler": macos/system_profiler.md
          - "tweaks": macos/tweaks.md
      - "Unix Commands":
          - "apropos": unix/apropos.md
          - "apt": unix/apt.md
          - "awk": unix/awk.md
          - "base64": unix/base64.md
          - "biosdecode": unix/biosdecode.md
          - "blkid": unix/blkid.md
          - "cal": unix/cal.md
          - "cat": unix/cat.md
          - "chage": unix/chage.md
          - "chmod": unix/chmod.md
          - "chsh": unix/chsh.md
          - "comm": unix/comm.md
          - "crontab": unix/crontab.md
          - "cut": unix/cut.md
          - "date": unix/date.md
          - "dd": unix/dd.md
          - "delv": unix/delv.md
          - "df": unix/df.md
          - "diff": unix/diff.md
          - "dig": unix/dig.md
          - "dmesg": unix/dmesg.md
          - "faketime": unix/faketime.md
          - "fdisk": unix/fdisk.md
          - "file": unix/file.md
          - "find": unix/find.md
          - "fls": unix/fls.md
          - "free": unix/free.md
          - "ftp": unix/ftp.md
          - "ghostscript": unix/ghostscript.md
          - "gpg": unix/gpg.md
          - "grep": unix/grep.md
          - "groupadd": unix/groupadd.md
          - "groupdel": unix/groupdel.md
          - "hdparm": unix/hdparm.md
          - "head": unix/head.md
          - "history": unix/history.md
          - "host": unix/host.md
          - "ifconfig": unix/ifconfig.md
          - "iotop": unix/iotop.md
          - "ip": unix/ip.md
          - "iwconfig": unix/iwconfig.md
          - "journalctl": unix/journalctl.md
          - "kill": unix/kill.md
          - "ln": unix/ln.md
          - "locate": unix/locate.md
          - "ls": unix/ls.md
          - "lsb_release": unix/lsb_release.md
          - "lsblk": unix/lsblk.md
          - "lshw": unix/lshw.md
          - "lsmod": unix/lsmod.md
          - "lspci": unix/lspci.md
          - "lsusb": unix/lsusb.md
          - "lvextend": unix/lvextend.md
          - "md5sum": unix/md5sum.md
          - "mkdir": unix/mkdir.md
          - "mkpasswd": unix/mkpasswd.md
          - "modprobe": unix/modprobe.md
          - "mount": unix/mount.md
          - "mtr": unix/mtr.md
          - "nc": unix/nc.md
          - "ncdu": unix/ncdu.md
          - "netplan": unix/netplan.md
          - "netstat": unix/netstat.md
          - "network-manager": unix/network-manager.md
          - "nm connection editor": unix/nm connection editor.md
          - "nmcli": unix/nmcli.md
          - "nslookup": unix/nslookup.md
          - "ntp": unix/ntp.md
          - "passwd": unix/passwd.md
          - "pdbedit": unix/pdbedit.md
          - "ps": unix/ps.md
          - "rev": unix/rev.md
          - "scp": unix/scp.md
          - "script": unix/script.md
          - "sed": unix/sed.md
          - "sha1sum": unix/sha1sum.md
          - "sha256sum": unix/sha256sum.md
          - "shuf": unix/shuf.md
          - "sort": unix/sort.md
          - "split": unix/split.md
          - "ss": unix/ss.md
          - "strings": unix/strings.md
          - "sudo": unix/sudo.md
          - "sudoedit": unix/sudoedit.md
          - "systemctl": unix/systemctl.md
          - "tail": unix/tail.md
          - "tar": unix/tar.md
          - "tee": unix/tee.md
          - "tftp": unix/tftp.md
          - "timedatectl": unix/timedatectl.md
          - "touch": unix/touch.md
          - "tr": unix/tr.md
          - "uname": unix/uname.md
          - "upower": unix/upower.md
          - "vimdiff": unix/vimdiff.md
          - "watch": unix/watch.md
          - "wc": unix/wc.md
          - "wget": unix/wget.md
          - "xargs": unix/xargs.md
          - "xxd": unix/xxd.md
      - "Windows Commands":
          - "azureAD": windows/azureAD.md
          - "cmd": windows/cmd.md
          - "godmode": windows/godmode.md
          - "ipconfig": windows/ipconfig.md
          - "nbtstat": windows/nbtstat.md
          - "net group": windows/net group.md
          - "net user": windows/net user.md
          - "net view": windows/net view.md
          - "netsh": windows/netsh.md
          - "nltest": windows/nltest.md
          - "nslookup": windows/nslookup.md
          - "powershell": windows/powershell.md
          - "regedit": windows/regedit.md
          - "route": windows/route.md
          - "schtasks": windows/schtasks.md